.\"-
.\" Copyright 2004-2005 Colin Percival
.\" Copyright 2018 Kris Moore
.\" All rights reserved
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted providing that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd July 1, 2018
.Dt PORTSNAP 8
.Os FreeBSD
.Sh NAME
.Nm portsnap
.Nd Extract and update snapshots of the ports tree from git
.Sh SYNOPSIS
.Nm
.Op Fl I
.Op Fl b Ar gitbranch
.Op Fl f Ar conffile
.Op Fl p Ar portsdir
.Op Fl r Ar gitremote
.Cm command ...
.Op Ar path
.Sh DESCRIPTION
The
.Nm
tool is used to extract and update
the
.Fx
ports tree.
.Pp
In a normal update operation,
.Nm
will routinely restore modified files to their unmodified state and
delete unrecognized local files.
.Sh OPTIONS
The following options are supported:
.Bl -tag -width "-f conffile"
.It Fl f Ar conffile
Read the configuration from
.Ar conffile .
(default:
.Pa /etc/portsnap.conf )
.It Fl p Ar portsdir
When extracting or updating an uncompressed snapshot,
operate on the directory
.Ar portsdir .
(default:
.Pa /usr/ports/ ,
or as given in the configuration file.)
.It Fl r Ar gitremote
Pull ports tree from specified git remote.
(default: https://github.com/trueos/trueos-ports, or as given in the
configuration file.)
.Sh COMMANDS
The
.Cm command
can be any one of the following:
.Bl -tag -width "-f conffile"
.Cm cron
command.
.It cron
Sleep a random amount of time between 1 and 3600 seconds,
then operate as if the
.Cm update
command was specified.
As the name suggests, this command is designed for running
from
.Xr cron 8 ;
the random delay serves to minimize the probability that
a large number of machines will simultaneously attempt to
fetch updates.
.It extract
Extract a ports tree, replacing existing files and directories.
NOTE: This will remove anything occupying the location where
files or directories are being extracted; in particular, any
changes made locally to the ports tree (for example, adding new
patches) will be silently obliterated.
.Pp
Only run this command to initialize your portsnap-maintained
ports tree for the first time, if you wish to start over with
a clean, completely unmodified tree, or if you wish to extract
a specific part of the tree (using the
.Ar path
option).
.It update
Update a ports tree extracted using the
.Cm extract
command.
You must run this command to apply changes to your ports tree
after downloading updates via the
.Cm cron
commands.
Again, note that in the parts of the ports tree which are being
updated, any local changes or additions will be removed.
.It auto
Run
.Cm cron
depending on whether stdin is a terminal; then run
.Cm update
or
.Cm extract
depending on whether
.Ar portsdir
exists.
.El
.Sh TIPS
.Bl -bullet
.It
If your clock is set to local time, adding the line
.Pp
.Dl 0 3 * * * root /usr/sbin/portsnap cron
.Pp
to
.Pa /etc/crontab
is a good way to make sure you always have
an up-to-date snapshot of the ports tree available which
can quickly be extracted into
.Pa /usr/ports .
If your clock is set to UTC, please pick a random time other
than 3AM, to avoid overly imposing an uneven load on the
server(s) hosting the snapshots.
.Sh FILES
.Bl -tag -width "/etc/portsnap.conf"
.It Pa /etc/portsnap.conf
Default location of the portsnap configuration file.
.It Pa /var/db/portsnap
Default location where compressed snapshots are stored.
.It Pa /usr/ports
Default location where the ports tree is extracted.
.El
.Sh EXAMPLES
Fetch the repo and create the
.Xr ports 7
tree under
.Pa /usr/ports :
.Dl Nm Ar extract
.Pp
Update the ports tree:
.Dl Nm Ar update
.Sh SEE ALSO
.Xr fetch 1 ,
.Xr sha256 1 ,
.Xr fetch 3 ,
.Xr portsnap.conf 5 ,
.Xr pkg 7 ,
.Xr pkg-version 8
.Sh AUTHORS
.An Colin Percival Aq Mt cperciva@FreeBSD.org
.An Kris Moore Aq Mt kmoore@FreeBSD.org
