# $FreeBSD$

PACKAGE=runtime

FILES=          bootmisc fsck ipfw ldconfig localmount moused netmount powerd rarpd \
		savecore staticroute swap syscons tmpfiles urandom

NO_OBJ=
FILESDIR=       /etc/conf.d
FILESMODE=      755

.include <bsd.prog.mk>

