# $FreeBSD$

FILES=          bootmisc fsck hostname ipfw localmount modules moused netmount network powerd rarpd savecore staticroute \
		swap syscons tmpfiles urandom

NO_OBJ=
FILESDIR=       /etc/conf.d
FILESMODE=      755

.include <bsd.prog.mk>

