# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/awk

FILES=	dependency_loop.awk \
	humanize.awk \
	json.awk \
	json_jail.awk \
	json_top.awk \
	parse_MOVED.awk \
	processonelog2.awk \
	siginfo_buildtime.awk

FILESDIR=	/usr/share/poudirere/awk
FILESMODE=	755

.include <bsd.prog.mk>
