# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/html/assets/bootstrap-3.1.1/js

FILES=	bootstrap.min.js

FILESDIR=	/usr/share/poudirere/html/assets/bootstrap-3.1.1/js
FILESMODE=	644

.include <bsd.prog.mk>
