# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/html/assets/DataTables-1.10.0/images

FILES=	back_disabled.png \
	back_enabled.png \
	back_enabled_hover.png \
	forward_disabled.png \
	forward_enabled_hover.png \
	sort_asc.png \
	sort_asc_disabled.png \
	sort_both.png \
	sort_desc.png \
	sort_desc_disabled.png

FILESDIR=	/usr/share/poudriere/html/assets/DataTables-1.10.0/images
FILESMODE=	644

.include <bsd.prog.mk>
