# $FreeBSD$

FILES= functions.sh gendepends.sh init.sh openrc-run.sh rc-functions.sh rc-mount.sh runit.sh \
       start-stop-daemon.sh supervise-daemon.sh

NO_OBJ=
FILESDIR=       /libexec/rc/sh
FILESMODE=      755

.include <bsd.prog.mk>

