# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/html/assets

SUBDIR=	DataTables-1.10.0 \
	bootstrap-3.1.1

FILES=	favicon.ico \
	jquery-1.11.1.js \
	jquery-1.11.1.min.js \
	jquery-1.11.1.min.map \
	jquery.dataTables.rowGrouping-1.2.9.js \
	logo.svg \
	poudriere.css \
	poudriere.js

FILESDIR=	/usr/share/poudriere/html/assets
FILESMODE=	644

.include <bsd.prog.mk>
