# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/html/assets/bootstrap-3.1.1/fonts

FILES=	glyphicons-halflings-regular.eot \
	glyphicons-halflings-regular.svg \
	glyphicons-halflings-regular.ttf \
	glyphicons-halflings-regular.woff

FILESDIR=	/usr/share/poudriere/html/assets/bootstrap-3.1.1/fonts
FILESMODE=	644

.include <bsd.prog.mk>
