#!/bin/sh
#
# $OpenBSD: ldapd,v 1.2 2011/09/16 10:13:24 robert Exp $
# $FreeBSD$

# PROVIDE: ldapd
# REQUIRE: DAEMON FILESYSTEMS devfs
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="ldapd"
desc="LDAP Daemon"
rcvar="ldapd_enable"
command="/usr/sbin/${name}"

load_rc_config "$name"
run_rc_command "$1"
