# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/html

SUBDIR=	assets

FILES=	build.html \
	index.html \
	jail.html \
	robots.txt

FILESDIR=	/usr/share/poudriere/html
FILESMODE=	644

.include <bsd.prog.mk>
