.\"
.\" Copyright (c) 2017 TrueOS Project <jmaloney@ixsystems.com>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd February 21, 2017
.Dt JINIT 8
.Os
.Sh NAME
.Nm jinit
.Nd "create jails"
.Sh SYNOPSIS
.Nm
.Op jail
.Op Fl n
.Op interface
.Sh DESCRIPTION
The
.Nm
utility creates the specified jail.  It will check to ensure that no other jail 
exists with the specified name.  Optionally an IP alias for the jail can be added.  
Other jail parameters can be modified in /etc/conf.d/jail.$jailname.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl n
Assign IP alias to jail.  This requires an interface argument.  Example: jinit -n 
192.168.0.2 re0
.El
.Sh SEE ALSO
.Xr jail_get 2 ,
.Xr libxo 3 ,
.Xr xo_parse_args 3 ,
.Xr jail 8 ,
.Xr jexec 8,
.Xr jbootstrap 8,
.Xr jdestroy 8
