#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD$

PACKAGE=runtime
PROG=	shutdown
MAN=	shutdown.8
LINKS=	${BINDIR}/poweroff ${BINDIR}/shutdown
MLINKS=	shutdown.8 poweroff.8

BINOWN=	root
BINGRP=	operator
BINMODE=4554

.include <bsd.prog.mk>
