#!/bin/sh
# $FreeBSD$

set -e

scriptdir=$(cd $(dirname $0) && pwd)
fwdir=$scriptdir/../../../contrib/dev/drm2/radeonkmsfw

for dir in $scriptdir/*; do
	if [ ! -d $dir ]; then
		continue
	fi
	rm -rf $dir
done

for file in $fwdir/*.uu; do
	base=$(basename $file)
	img=${base%.bin.uu}
	kmodname=radeon_$img"_bin"
	name=radeon/$img".bin"
	echo "Image: $img"

	mkdir -p $scriptdir/$img
	cat > $scriptdir/$img/Makefile <<EOF
# \$FreeBSD$

KMOD=	$kmodname
NAME=	$name
IMG=	$img

.include <bsd.kmod.mk>
EOF
done
