# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/include

FILES=	cache.sh \
	colors.pre.sh \
	colors.sh \
	common.sh.dragonfly \
	common.sh.freebsd \
	display.sh \
	fs.sh \
	hash.sh \
	html.sh \
	parallel.sh \
	shared_hash.sh \
	util.sh

FILESDIR=	/usr/share/poudirere/include
FILESMODE=	755

.include <bsd.prog.mk>
