# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/html/assets/DataTables-1.10.0/js

FILES=	jquery.dataTables.min.js

FILESDIR=	/usr/share/poudriere/html/assets/DataTables-1.10.0/js
FILESMODE=	644

.include <bsd.prog.mk>
