# $FreeBSD$

FILES=          adjkerntz bootmisc cron devd dumpon encswap fsck functions.sh hostid hostname ipfw jail \
		local localmount loopback mixer modules modules-load moused netmount network newsyslog \
		nscd osclock pf powerd rarpd rc-enabled root rpcbind runsvdir s6-svscan savecache savecore \
		sshd staticroute swap swclock syscons sysctl syslogd tmpfiles.setup urandom zfs zvol

NO_OBJ=
FILESDIR=       /etc/init.d
FILESMODE=      755

.include <bsd.prog.mk>

