#!/bin/sh
#
# Copyright (c) 2017 Joe Maloney. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#       Email: Joe Maloney <jmaloney@ixsystems.com>
#

# Only run as superuser
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Only run if pkg is not running
while :
do
  if pgrep pkg ; then
    echo "Another process is still running pkg"
    sleep 3
  else
    break
  fi
done

# Define the location of bootstrap
bootstrap=/usr/jails/.bootstrap/

clean_packages()
{
  rm -rf $bootstrap
  if [ ! -d "${bootstrap}" ] ; then
  mkdir $bootstrap
  fi
}

fetch_packages()
{
  cd $bootstrap
  fetch http://pkg.cdn.trueos.org/packages/master/amd64-base/fbsd-distrib.txz
  pc-updatemanager pkgcheck
  pkg fetch -r trueos-base -a -y -o $bootstrap
  pkg fetch -y -o $bootstrap -r trueos-major pkg
  pkg fetch -y -o $bootstrap -r trueos-major pc-updatemanager
}


bootstrap_prompt()
{
  while true; do
      read -p "Are you sure you want to bootstrap for jails?" yn
      case $yn in
          [Yy]* ) clean_packages; fetch_packages; break;;
          [Nn]* ) exit;;
          * ) echo "Please answer yes or no.";;
      esac
  done
}

# Execute our functions
case $1 in
        -y)
        clean_packages
        fetch_packages
        ;;
        *)
        bootstrap_prompt
        ;;
esac
