# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/html/assets/DataTables-1.10.0/css

FILES=	jquery.dataTables.min.css \
	jquery.dataTables_themeroller.min.css

FILESDIR=	/usr/share/poudirere/html/assets/DataTables-1.10.0/css
FILESMODE=	644

.include <bsd.prog.mk>
