# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere/html/assets/bootstrap-3.1.1/css

FILES=	bootstrap-theme.min.css \
	bootstrap.min.css

FILESDIR=	/usr/share/poudriere/html/assets/bootstrap-3.1.1/css
FILESMODE=	644

.include <bsd.prog.mk>
