/*
 * This file was generated by the mkbuiltins program.
 */

#include <sys/cdefs.h>
#define BLTINCMD 0
#define ALIASCMD 1
#define BGCMD 2
#define BINDCMD 3
#define BREAKCMD 4
#define CDCMD 5
#define COMMANDCMD 6
#define DOTCMD 7
#define ECHOCMD 8
#define EVALCMD 9
#define EXECCMD 10
#define EXITCMD 11
#define LETCMD 12
#define EXPORTCMD 13
#define FALSECMD 14
#define FGCMD 15
#define FREEBSD_WORDEXPCMD 16
#define GETOPTSCMD 17
#define HASHCMD 18
#define HISTCMD 19
#define JOBIDCMD 20
#define JOBSCMD 21
#define KILLCMD 22
#define LOCALCMD 23
#define PRINTFCMD 24
#define PWDCMD 25
#define READCMD 26
#define RETURNCMD 27
#define SETCMD 28
#define SETVARCMD 29
#define SHIFTCMD 30
#define TESTCMD 31
#define TIMESCMD 32
#define TRAPCMD 33
#define TRUECMD 34
#define TYPECMD 35
#define ULIMITCMD 36
#define UMASKCMD 37
#define UNALIASCMD 38
#define UNSETCMD 39
#define WAITCMD 40
#define WORDEXPCMD 41
#define CLOCKCMD 42
#define DIREMPTYCMD 43
#define LOCKED_MKDIRCMD 44
#define MKDIRCMD 45
#define MKFIFOCMD 46
#define MKTEMPCMD 47
#define PWAITCMD 48
#define REALPATHCMD 49
#define RENAMECMD 50
#define RMDIRCMD 51
#define SETPROCTITLECMD 52
#define SLEEPCMD 53
#define TOUCHCMD 54
#define UNLINKCMD 55

#define BUILTIN_SPECIAL 0x80

extern int (*const builtinfunc[])(int, char **);
extern const unsigned char builtincmd[];

int bltincmd(int, char **);
int aliascmd(int, char **);
int bgcmd(int, char **);
int bindcmd(int, char **);
int breakcmd(int, char **);
int cdcmd(int, char **);
int commandcmd(int, char **);
int dotcmd(int, char **);
int echocmd(int, char **);
int evalcmd(int, char **);
int execcmd(int, char **);
int exitcmd(int, char **);
int letcmd(int, char **);
int exportcmd(int, char **);
int falsecmd(int, char **);
int fgcmd(int, char **);
int freebsd_wordexpcmd(int, char **);
int getoptscmd(int, char **);
int hashcmd(int, char **);
int histcmd(int, char **);
int jobidcmd(int, char **);
int jobscmd(int, char **);
int killcmd(int, char **);
int localcmd(int, char **);
int printfcmd(int, char **);
int pwdcmd(int, char **);
int readcmd(int, char **);
int returncmd(int, char **);
int setcmd(int, char **);
int setvarcmd(int, char **);
int shiftcmd(int, char **);
int testcmd(int, char **);
int timescmd(int, char **);
int trapcmd(int, char **);
int truecmd(int, char **);
int typecmd(int, char **);
int ulimitcmd(int, char **);
int umaskcmd(int, char **);
int unaliascmd(int, char **);
int unsetcmd(int, char **);
int waitcmd(int, char **);
int wordexpcmd(int, char **);
int clockcmd(int, char **);
int diremptycmd(int, char **);
int locked_mkdircmd(int, char **);
int mkdircmd(int, char **);
int mkfifocmd(int, char **);
int mktempcmd(int, char **);
int pwaitcmd(int, char **);
int realpathcmd(int, char **);
int renamecmd(int, char **);
int rmdircmd(int, char **);
int setproctitlecmd(int, char **);
int sleepcmd(int, char **);
int touchcmd(int, char **);
int unlinkcmd(int, char **);

static inline int
safe_builtin_always(int idx)
{
	if (idx == BLTINCMD || 
	    idx == COMMANDCMD || 
	    idx == ECHOCMD || 
	    idx == FALSECMD || 
	    idx == JOBIDCMD || 
	    idx == JOBSCMD || 
	    idx == KILLCMD || 
	    idx == PRINTFCMD || 
	    idx == PWDCMD || 
	    idx == TESTCMD || 
	    idx == TIMESCMD || 
	    idx == TRUECMD || 
	    idx == TYPECMD || 
	    idx == CLOCKCMD || 
	    idx == DIREMPTYCMD || 
	    idx == MKDIRCMD || 
	    idx == MKFIFOCMD || 
	    idx == MKTEMPCMD || 
	    idx == REALPATHCMD || 
	    idx == RENAMECMD || 
	    idx == RMDIRCMD || 
	    idx == SLEEPCMD || 
	    idx == UNLINKCMD)
		return (1);
	return(0);
}
