#!/bin/sh
# Copyright (c) 2007-2015 The OpenRC Authors.
# See the Authors file at the top-level directory of this distribution and
# https://github.com/OpenRC/openrc/blob/master/AUTHORS
#
# This file is part of OpenRC. It is subject to the license terms in
# the LICENSE file found in the top-level directory of this
# distribution and at https://github.com/OpenRC/openrc/blob/master/LICENSE
# This file may not be copied, modified, propagated, or distributed
#    except according to the terms contained in the LICENSE file.

# If $TERM is not set then assume default of cons25
# This gives us a nice colour boot :)
[ -z "$TERM" -o "$TERM" = "dumb" ] && TERM="cons25" && export TERM

# Handle interrupts
trap : SIGINT
trap "echo 'Boot interrupted'; exit 1" SIGQUIT

dlv=`/sbin/sysctl -n vfs.nfs.diskless_valid 2> /dev/null`
if [ ${dlv:=0} -ne 0 -o -f /etc/diskless ]; then
  sh /etc/rc.initdiskless
fi

# This is for install media which is R/O. We need /etc and
# /usr/local/etc to be R/W for services like networking
# mouse and other to start on live/install media
/sbin/mount -t tmpfs tmpfs /tmp
#Make temporary staging areas in /tmp
/bin/mkdir -p /tmp/var
/bin/mkdir -p /tmp/etc
/bin/mkdir -p /tmp/localetc
#Copy any existing files to the staging area
/bin/cp -r /var/* /tmp/var/
/bin/cp -r /etc/* /tmp/etc/
/bin/cp -r /usr/local/etc/* /tmp/localetc/
#Create the read-write tmpfs mountpoints
/sbin/mount -t tmpfs tmpfs /var/
/sbin/mount -t tmpfs tmpfs /etc/
/sbin/mount -t tmpfs tmpfs /usr/local/etc/
#Move staged files into read/write mountpoints
/bin/mv /tmp/var/* /var/
/bin/mv /tmp/etc/* /etc/
/bin/mv /tmp/localetc/* /usr/local/etc/
#Cleanup staging areas
/bin/rmdir /tmp/var/
/bin/rmdir /tmp/etc/
/bin/rmdir /tmp/localetc/
#Create any empty subdirs as needed
/bin/mkdir -p /var/tmp

# Start OpenRC Now
/sbin/openrc sysinit || exit 1
/sbin/openrc boot || exit 1
/sbin/openrc default || exit 1

# Sleep a tick first, which prevents from odd services from crashing
sleep 1

# We don't actually care if rc default worked or not, we should exit 0
# to allow logins
exit 0
