# $FreeBSD$

FILES=          adjkerntz bootmisc dumpon fsck hostid hostname localmount loopback modules network newsyslog \
		root savecore staticroute swap syscons sysctl syslogd urandom zfs zvol

NO_OBJ=
FILESDIR=       /etc/runlevels/boot
FILESMODE=      755

.include <bsd.prog.mk>

