# $FreeBSD$

CONFS+=	${SRCTOP}/usr.sbin/sendmail/mail/access.sample
CONFS+=	${SRCTOP}/usr.sbin/sendmail/mail/aliases
CONFS+=	${SRCTOP}/usr.sbin/sendmail/mail/mailer.conf
CONFS+=	${SRCTOP}/usr.sbin/sendmail/sendmailetc/freebsd.mc
CONFS+=	${SRCTOP}/usr.sbin/sendmail/sendmailetc/freebsd.submit.mc
CONFS+=	${SRCTOP}/usr.sbin/sendmail/sendmailetc/freefall.mc
CONFSDIR=	/etc/mail
CONFSMODE=	644

FILES+=	${SRCTOP}/usr.sbin/sendmail/mail/mailertable.sample
FILES+=	${SRCTOP}/usr.sbin/sendmail/mail/virtusertable.sample
FILES+=	${SRCTOP}/usr.sbin/sendmail/mail/README
FILESDIR=	/etc/mail
FILESMODE=	644

.include <bsd.prog.mk>
