# $FreeBSD$

.include <bsd.init.mk>

FILESDIR=	/boot/lua

FILES=	brand-trident.lua \
  brand-trueos.lua \
	cli.lua \
	color.lua \
	config.lua \
	core.lua \
	drawer.lua \
	hook.lua \
	loader.lua \
	logo-beastie.lua \
	logo-beastiebw.lua \
	logo-fbsdbw.lua \
	logo-orb.lua \
	logo-orbbw.lua \
	logo-trident.lua \
	menu.lua \
	password.lua \
	screen.lua

.include <bsd.prog.mk>
