#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD$

CONFS=	sysctl.conf
CONFSDIR_sysctl.conf=   /etc/defaults
CONFSMODE_sysctl.conf=  600
PACKAGE=runtime
PROG=	sysctl
WARNS?=	3
MAN=	sysctl.8

.include <bsd.prog.mk>
