# $FreeBSD$

BINDIR=/libexec/poudriere

SUBDIR= cachec
SUBDIR= cached
SUBDIR= clock
SUBDIR= cpdup
SUBDIR=	dirempty
SUBDIR=	dirwatch
SUBDIR=	jexecd
SUBDIR=	locked_mkdir
SUBDIR=	nc
SUBDIR=	poudriered
SUBDIR=	ptsort
SUBDIR=	pwait
SUBDIR=	rename
SUBDIR=	rexec
SUBDIR=	sh
SUBDIR=	timeout
SUBDIR=	timestamp
SUBDIR=	tsort
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>

