# $FreeBSD$

BINDIR=/libexec/poudriere

SUBDIR= cachec \
	cached \
	clock \
	cpdup \
	dirempty \
	dirwatch \
	jexecd \
	locked_mkdir \
	nc \
	poudriered \
	ptsort \
	pwait \
	rename \
	rexec \
	sh \
	timeout \
	timestamp \
	tsort
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>

