# $FreeBSD$

PTOP=	${SRCTOP}/contrib/poudriere/src/share
.PATH:	${PTOP}/poudriere

SUBDIR=	awk \
	html \
	include

FILES=	api.sh \
	bulk.sh \
	common.sh \
	daemon.sh \
	distclean.sh \
	image.sh \
	jail.sh \
	logclean.sh \
	options.sh \
	pkgclean.sh \
	ports.sh \
	processonelog.sh \
	queue.sh \
	status.sh \
	testport.sh

FILESDIR=	/usr/share/poudriere
FILESMODE=	755

.include <bsd.prog.mk>
