# freebsd
SYSCONFDIR=	/etc
SBINDIR=	/sbin
LIBDIR=		/lib
LIBEXECDIR=	/libexec
DBDIR=		/var/db/dhcpcd
RUNDIR=		/var/run
LIBDIR=		/lib
MANDIR=		/usr/share/man
DATADIR=	/usr/share
CPPFLAGS+=	-DHAVE_CONFIG_H
CFLAGS+=	-g -Wall -Wextra
CFLAGS+=	-Wmissing-prototypes -Wmissing-declarations
CFLAGS+=	-Wmissing-format-attribute -Wnested-externs
CFLAGS+=	-Winline -Wcast-align -Wcast-qual -Wpointer-arith
CFLAGS+=	-Wreturn-type -Wswitch -Wshadow
CFLAGS+=	-Wcast-qual -Wwrite-strings
CFLAGS+=	-Wformat=2
CFLAGS+=	-Wpointer-sign -Wmissing-noreturn
CFLAGS+=	-Wredundant-decls
CFLAGS+=	-Wconversion
CFLAGS+=	-Wstrict-overflow
CPPFLAGS+=	-D_GNU_SOURCE
DHCPCD_SRCS+=	if-bsd.c
CPPFLAGS+=	-DINET
DHCPCD_SRCS+=	dhcp.c ipv4.c bpf.c
CPPFLAGS+=	-DARP
DHCPCD_SRCS+=	arp.c
CPPFLAGS+=	-DARPING
CPPFLAGS+=	-DIPV4LL
DHCPCD_SRCS+=	ipv4ll.c
CPPFLAGS+=	-DINET6
DHCPCD_SRCS+=	ipv6.c ipv6nd.c
CPPFLAGS+=	-DDHCP6
DHCPCD_SRCS+=	dhcp6.c
CPPFLAGS+=	-DAUTH
SRCS+=		auth.c
CRYPT_SRCS+=	crypt/hmac_md5.c
CRYPT_SRCS+=	${MD5_SRC} ${SHA256_SRC}
DHCPCD_SRCS+=	dhcpcd-embedded.c
COMPAT_SRCS+=	compat/pidfile.c
COMPAT_SRCS+=	compat/strtoi.c compat/strtou.c
MD5_SRC=
LDADD+=		-lmd
SHA256_SRC=
LDADD+=		-lmd
SERVICEEXISTS=	
SERVICECMD=	
SERVICESTATUS=	
STATUSARG=	onestatus
YPDOMAIN_DIR=
YPDOMAIN_SUFFIX=
HOOKSCRIPTS=	50-ntp.conf
EGHOOKSCRIPTS=	50-ypbind
